### ISSUE TITLE
For stale profile accounts, all the profile pictures should have the fallback not just the avatar

### ISSUE THREAD

**Issue by edisonqu** [TenacityLabs/unfollowedlol-landing-page#2]
For e.g.
https://unfollowed.lol/user/ari.b.12

<img width="936" alt="image" src="https://github.com/TenacityLabs/unfollowedlol-app/assets/63879791/afa238aa-15b6-473c-8f90-a937cf2535cf">

**Comment by andrewhdurnford** [comment]
fixed
